//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu11
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// F1.
    /// </summary>
    //  *** Start programmer edit section *** (F1 CustomAttributes)

    //  *** End programmer edit section *** (F1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("F1E", new string[0])]
    [View("F1L", new string[0])]
    public class F1 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (F1 CustomMembers)

        //  *** End programmer edit section *** (F1 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "F1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View F1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("F1E", typeof(IIS.mu11.F1));
                }
            }
            
            /// <summary>
            /// "F1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View F1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("F1L", typeof(IIS.mu11.F1));
                }
            }
        }
    }
}
